name: GradleRIO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spotless:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2022-18.04    
    steps:
      - uses: actions/checkout@v2   
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew      
      - name: Check for code formatting
        run: ./gradlew spotlessCheck       
        
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2022-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile and run tests on robot code
      run: ./gradlew build -x spotlessJavaCheck
